owner: bgord
repo: statuses

sites:
  - name: RAOK
    url: https://raok.bgord.me
  - name: TRACKERS
    url: https://trackers.bgord.me
  - name: SHOWCASE
    url: https://showcase.bgord.me

status-website:
  baseUrl: /statuses
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: bgord/statuses
  introTitle: "**bgord/statuses**"
  navbar:
    - title: Statuses
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
      
workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/15 * * * *"
