owner: bgord
repo: statuses

sites:
  - name: RAOK
    url: https://raok.bgord.me

status-website:
  baseUrl: /statuses
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Statuses
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a bgord status page which uses **real-time** data from our [GitHub repository](https://github.com/bgord/statuses). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
