owner: bgord
repo: statuses

sites:
  - name: RAOK
    url: https://raok.bgord.space/healthcheck
    method: "GET"
    headers:
      - "Authorization: Basic $GH_BASIC_AUTH_SECRET"
    expectedStatusCodes:
      - 200
      - 429

  - name: Journal
    url: https://journal.bgord.space/api/healthcheck
    method: "GET"
    headers:
      - "Authorization: Basic $GH_BASIC_AUTH_SECRET"
    expectedStatusCodes:
      - 200
      - 429

  - name: lobbygow
    url: https://lobbygow.bgord.space/api/healthcheck
    method: "GET"
    headers:
      - "Authorization: Basic $GH_BASIC_AUTH_SECRET"
    expectedStatusCodes:
      - 200
      - 429

  - name: SHOWCASE
    url: https://showcase.bgord.space/api/healthcheck
    method: "GET"
    headers:
      - "Authorization: Basic $GH_BASIC_AUTH_SECRET"
    expectedStatusCodes:
      - 200
      - 429

  - name: panopticon
    url: https://panopticon.bgord.space/api/healthcheck
    method: "GET"
    headers:
      - "Authorization: Basic $GH_BASIC_AUTH_SECRET"
    expectedStatusCodes:
      - 200
      - 429

  - name: workouts
    url: https://workouts.bgord.space/api/healthcheck
    method: "GET"
    headers:
      - "Authorization: Basic $GH_BASIC_AUTH_SECRET"
    expectedStatusCodes:
      - 200
      - 429

status-website:
  baseUrl: /statuses
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: bgord/statuses
  introTitle: "**bgord/statuses**"
  navbar:
    - title: Statuses
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/15 * * * *"
